apiVersion: v1
kind: ReplicationController
metadata:
  name: web_nginx_rc
spec:
  replicas: 3
  selector:
    app: web_nginx_rc
  template:
    metadata:
      name: web_nginx_rc
      labels:
        app: web_nginx_rc
    spec:
      containers:
      - name: web_nginx_rc
        image: nginx
        ports:
        - containerPort: 3300
